/**
 * @generated by scripts/set-rn-version.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict
 */

exports.version = {
  major: 0,
  minor: 74,
  patch: 0,
  prerelease: 'nightly-20231027-535b187f0',
};
