parameters:
  - name: appleBuildMatrix
    type: object
    default:
      - name: macos_debug_oldarch_jsc
        friendly_name: 'macOS, Old Arch, JSC'
        sdk: macosx
        configuration: Debug
        scheme: RNTester-macOS
        packager_platform: 'macos'
        new_arch_enabled: '0'
        use_hermes: '0'
      - name: macos_debug_newarch_jsc
        friendly_name: 'macOS, New Arch, JSC'
        sdk: macosx
        configuration: Debug
        scheme: RNTester-macOS
        packager_platform: 'macos'
        new_arch_enabled: '1'
        use_hermes: '0'
      - name: ios_debug_oldarch_jsc
        friendly_name: 'iOS, Old Arch, JSC'
        sdk: iphonesimulator
        configuration: Debug
        scheme: RNTester
        packager_platform: 'ios'
        new_arch_enabled: '0'
        use_hermes: '0'
      - name: ios_debug_newarch_jsc
        friendly_name: 'iOS, New Arch, JSC'
        sdk: iphonesimulator
        configuration: Debug
        scheme: RNTester
        packager_platform: 'ios'
        new_arch_enabled: '1'
        use_hermes: '0'
      - name: xros_debug_oldarch_jsc
        friendly_name: 'xrOS, Old Arch, JSC'
        sdk: xrsimulator
        configuration: Debug
        scheme: RNTester-visionOS
        packager_platform: 'ios'
        new_arch_enabled: '0'
        use_hermes: '0'
      - name: xros_debug_newarch_jsc
        friendly_name: 'xrOS, New Arch, JSC'
        sdk: xrsimulator
        configuration: Debug
        scheme: RNTester-visionOS
        packager_platform: 'ios'
        new_arch_enabled: '1'
        use_hermes: '0'
      - name: macos_debug_oldarch_hermes
        friendly_name: 'macOS, Old Arch, Hermes'
        sdk: macosx
        configuration: Debug
        scheme: RNTester-macOS
        packager_platform: 'macos'
        new_arch_enabled: '0'
        use_hermes: '1'
      - name: macos_debug_newarch_hermes
        friendly_name: 'macOS, New Arch, Hermes'
        sdk: macosx
        configuration: Debug
        scheme: RNTester-macOS
        packager_platform: 'macos'
        new_arch_enabled: '1'
        use_hermes: '1'
      - name: ios_debug_oldarch_hermes
        friendly_name: 'iOS, Old Arch, Hermes'
        sdk: iphonesimulator
        configuration: Debug
        scheme: RNTester
        packager_platform: 'ios'
        new_arch_enabled: '0'
        use_hermes: '1'
      - name: ios_debug_newarch_hermes
        friendly_name: 'iOS, New Arch, Hermes'
        sdk: iphonesimulator
        configuration: Debug
        scheme: RNTester
        packager_platform: 'ios'
        new_arch_enabled: '1'
        use_hermes: '1'
      # - name: xros_debug_oldarch_hermes
      #   friendly_name: 'xrOS, Old Arch, Hermes'
      #   sdk: xrsimulator
      #   configuration: Debug
      #   scheme: RNTester-visionOS
      #   packager_platform: 'ios'
      #   new_arch_enabled: '0'
      #   use_hermes: '1'
      # - name: xros_debug_newarch_hermes
      #   friendly_name: 'xrOS, New Arch, Hermes'
      #   sdk: xrsimulator
      #   configuration: Debug
      #   scheme: RNTester-visionOS
      #   packager_platform: 'ios'
      #   new_arch_enabled: '1'
      #   use_hermes: '1'

jobs:
  - ${{ each slice in parameters.appleBuildMatrix }}:
    - job: ${{ slice.name }}
      displayName: ${{ slice.friendly_name }}
      pool:
        vmImage: $(vmImageApple)
      timeoutInMinutes: 90
      cancelTimeoutInMinutes: 5
      steps:
        - template: /.ado/templates/apple-tools-setup.yml@self

        - script: |
            yarn install
          displayName: yarn install
        
        - template: /.ado/templates/build-rntester-steps.yml@self
          parameters:
            sdk: ${{ slice.sdk }}
            configuration: ${{ slice.configuration }}
            scheme: ${{ slice.scheme }}
            new_arch_enabled: ${{ slice.new_arch_enabled }}
            use_hermes: ${{ slice.use_hermes }}
        
        # https://github.com/microsoft/react-native-macos/issues/2297
        # Skip native tests as they tend to be flaky
        # - template: /.ado/templates/test-rntester-steps.yml@self
        #   parameters:
        #     sdk: ${{ slice.sdk }}
        #     configuration: ${{ slice.configuration }}
        #     scheme: ${{ slice.scheme }}
        #     packager_platform: ${{ slice.packager_platform }}