jobs:
- job: NPMPublish
  displayName: NPM Publish
  pool:
    name: cxeiss-ubuntu-20-04-large
    image: cxe-ubuntu-20-04-1es-pt
    os: linux
  variables:
    - name: BUILDSECMON_OPT_IN
      value: true
    
  timeoutInMinutes: 90
  cancelTimeoutInMinutes: 5
  templateContext:
    outputs:
      - output: pipelineArtifact
        targetPath: $(System.DefaultWorkingDirectory)
        artifactName: github-npm-js-publish
  steps:
    - checkout: self
      clean: true
      fetchFilter: blob:none
      persistCredentials: true

    - template: /.ado/templates/configure-git.yml@self

    - script: |
        yarn install
      displayName: Install npm dependencies

    - script: |
        node .ado/scripts/release.mjs --dry-run --verbose
      displayName: Release (dry run)
      condition: and(succeeded(), ne(variables['publish_react_native_macos'], '1'))

    # Disable Nightly publishing on the main branch
    - ${{ if endsWith(variables['Build.SourceBranchName'], '-stable') }}:
      - script: |
          git switch $(Build.SourceBranchName)
          RELEASE_TAG=$(tail -1 .ado/release-config.yml)
          node .ado/scripts/release.mjs --verbose --tag "$RELEASE_TAG" --token "$(npmAuthToken)"
        env:
          GITHUB_TOKEN: $(githubAuthToken)
        displayName: Release
        condition: and(succeeded(), eq(variables['publish_react_native_macos'], '1'))

    - script: |
        rm -f ~/.npmrc
      displayName: Remove NPM auth configuration
      condition: always()
