jobs:
  - job: react_native_test_app
    displayName: react-native-test-app
    pool:
      vmImage: $(VmImageApple)
    workspace:
      clean: all
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5
    steps:
      - template: /.ado/templates/apple-tools-setup.yml@self

      - template: /.ado/templates/verdaccio-publish.yml@self

      - script: |
          git clone --filter=blob:none --progress https://github.com/microsoft/react-native-test-app.git
        displayName: Clone react-native-test-app

      - script: |
          echo "##vso[task.setvariable variable=react_version]$(cat package.json | jq .peerDependencies.react)"
          echo "##vso[task.setvariable variable=react_native_version]$(cat package.json | jq '.dependencies."@react-native/codegen"')"
        displayName: 'Determine react-native version'
        workingDirectory: packages/react-native

      - script: |
          set -eo pipefail
          cat package.json |
            jq '.devDependencies["react"] = $(react_version)' |
            jq '.devDependencies["react-native"] = $(react_native_version)' |
            jq '.devDependencies["react-native-macos"] = "latest"' |
            jq 'del(.devDependencies["@react-native-community/cli"])' |
            jq 'del(.devDependencies["react-native-windows"])' > .package.json
          mv .package.json package.json
          cat package.json | jq .devDependencies
        displayName: Modify react-native-test-app dependencies
        workingDirectory: react-native-test-app

      - script: |
          set -eo pipefail
          cat package.json |
            jq '.dependencies["react"] = $(react_version)' |
            jq '.dependencies["react-native"] = $(react_native_version)' |
            jq '.dependencies["react-native-macos"] = "latest"' |
            jq '.devDependencies["@react-native-community/cli"] = "latest"' |
            jq '.devDependencies["@react-native-community/cli-platform-android"] = "latest"' |
            jq '.devDependencies["@react-native-community/cli-platform-ios"] = "latest"' |
            jq 'del(.dependencies["react-native-windows"])' > .package.json
          mv .package.json package.json
          cat package.json | jq .dependencies
        displayName: Modify example app dependencies
        workingDirectory: react-native-test-app/example

      - script: |
          $(Build.Repository.LocalPath)/.ado/scripts/verdaccio.sh configure
          yarn --no-immutable
        displayName: Install npm dependencies
        workingDirectory: react-native-test-app

      - script: |
          yarn build:macos || yarn build:macos
        displayName: Bundle JavaScript
        workingDirectory: react-native-test-app/example

      - script: |
          rm macos/Podfile.lock
          pod install --project-directory=macos
        displayName: Install Pods
        workingDirectory: react-native-test-app/example

      - script: |
          set -eo pipefail
          ../scripts/xcodebuild.sh macos/Example.xcworkspace build | xcbeautify
        displayName: Build Intel
        workingDirectory: react-native-test-app/example
        env:
          CCACHE_DISABLE: 1

      - script: |
          set -eo pipefail
          ../scripts/xcodebuild.sh macos/Example.xcworkspace clean
          ../scripts/xcodebuild.sh macos/Example.xcworkspace build ARCHS=arm64 | xcbeautify
        displayName: Build ARM
        workingDirectory: react-native-test-app/example
        env:
          CCACHE_DISABLE: 1
