# This file defines the Apple PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

variables:
  - template: /.ado/variables/vars.yml@self

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

stages:
  - stage: Build_And_Test
    displayName: 'Build and Test'
    dependsOn: []
    jobs:
      - template: /.ado/jobs/build-test-rntester.yml@self

  - stage: JSOnly
    dependsOn: []
    jobs:
      - template: /.ado/jobs/test-javascript.yml@self

      - template: /.ado/jobs/npm-publish-dry-run.yml@self

  - stage: Integration
    dependsOn: []
    jobs:
      - template: /.ado/jobs/test-react-native-macos-init.yml@self

  - stage: Validate_Peer_Dependency
    displayName: 'Validate Peer Dependency'
    dependsOn: []
    condition: and(succeeded(), contains(variables['System.PullRequest.TargetBranch'], '-stable'))
    jobs:
      - job: CheckRNPeerDependency
        displayName: 'react-native'
        pool:
          vmImage: $(vmImageApple)
        steps:
          - script: |
              set -eox pipefail
              if ! jq -e '.peerDependencies["react-native"]' packages/react-native/package.json > /dev/null; then
                echo "##vso[task.logissue type=error]react-native is not listed as a peerDependency in packages/react-native/package.json"
                exit 1
              fi
            displayName: 'Validate peerDependency in package.json'

      # - template: /.ado/jobs/react-native-test-app-integration.yml@self